schema: "classroom50/repo-config/v1"
classroom: "pac-ad2026"
assignment: "reto1-fase1-entornoaislado"
owner:
  username: "MaelTrevino"
  id: 181307124
  accepted_at: "2026-08-27T22:26:03Z"
source:
  owner: "PMVG-FCFM-AD2026"
  owner_id: 313567445
  repo: "Reto1_PAC"
  branch: "main"
